### ISSUE TITLE
[sandbox] Добавить в js-sandbox возможность подменять таймеры

### ISSUE THREAD

**Issue by nulladdict** [kontur-edu/Ulearn#205]
Это нужно для задач, с условной асинхронщиной, а-ля `setTimeout` / `setInterval`, скорее всего можно просто использовать [fake-timers](https://github.com/sinonjs/fake-timers)
Заодно обновить остальные возможности

**Comment by vorkulsky** [comment]
Привет. Лучше пришли МР.

Тебя интересуют изменения в файлах из этой папки: https://github.com/kontur-edu/Ulearn/tree/master/sandboxes/js-sandbox/container

**Comment by nulladdict** [comment]
Привет, да, я этим и собираюсь заниматься, создал issue, чтобы не потерять :)
