### ISSUE TITLE
Баг в валидаторе на лишние строки в начале метода

### ISSUE THREAD

**Issue by andgein** [kontur-edu/Ulearn#74]
@nikitosbobin

Валидатор некорректно обрабатывает (как минимум) однострочные комментарии в начале метода.

![image](https://user-images.githubusercontent.com/1853477/37539380-6415fa4e-2975-11e8-9362-3a6abe8bc894.png)

Конкретно эта валидация пока выключена — до тех пор, пока не починим.

**Comment by nikitosbobin** [comment]
Починил в последнем мёрж реквесте

**Comment by andgein** [comment]
Можно в пулл-реквесте писать в любом месте фразу «Fixes #74», и тогда баг автоматически закроется гитхабом при вливании пулл-реквеста. Магия :)
