### ISSUE TITLE
Баг в авто ревью при проверке больших задач

### ISSUE THREAD

**Issue by Griboedoff** [kontur-edu/Ulearn#81]
При использовании в return valueTuple авторевьюер ругается 
![image](https://user-images.githubusercontent.com/16411561/46574752-e739dc00-c9c1-11e8-97e4-6bf9384547d5.png)

**Comment by andgein** [comment]
Ага, известная проблема, скоро починим. (https://yt.skbkontur.ru/issue/ULEARN-43)
